<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Libros_model extends CI_Model
{

    public $table = 'libros';
    public $id = 'id';
    public $titulo = 'titulo';
    public $order = 'ASC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
    $this->db->or_like('imagenLibro', $q);
	$this->db->or_like('titulo', $q);
	$this->db->or_like('autor', $q);
	$this->db->or_like('anio', $q);
	$this->db->or_like('editor', $q);
	$this->db->or_like('isbn', $q);
	$this->db->or_like('idioma', $q);
	$this->db->or_like('precio', $q);
	$this->db->or_like('numPaginas', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->titulo, $this->order);
        $this->db->like('id', $q);
    $this->db->or_like('imagenLibro', $q);
	$this->db->or_like('titulo', $q);
	$this->db->or_like('autor', $q);
	$this->db->or_like('anio', $q);
	$this->db->or_like('editor', $q);
	$this->db->or_like('isbn', $q);
	$this->db->or_like('idioma', $q);
	$this->db->or_like('precio', $q);
	$this->db->or_like('numPaginas', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Libros_model.php */
/* Location: ./application/models/Libros_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-05-15 00:41:42 */
/* http://harviacode.com */