<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Vinos_model extends CI_Model
{

    public $table = 'vinos';
    public $id = 'id';
    public $nombre = 'nombre';
    public $order = 'DESC';
    public $orderAsc = 'ASC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->nombre, $this->orderAsc);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('nombre', $q);
	$this->db->or_like('tipo', $q);
	$this->db->or_like('cepa', $q);
	$this->db->or_like('anio', $q);
	$this->db->or_like('pais', $q);
	$this->db->or_like('imagen', $q);
	$this->db->or_like('color', $q);
	$this->db->or_like('nariz', $q);
	$this->db->or_like('boca', $q);
	$this->db->or_like('maridaje', $q);
	$this->db->or_like('precio', $q);
	$this->db->or_like('descripcion', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->nombre, $this->orderAsc);
        $this->db->like('id', $q);
	$this->db->or_like('nombre', $q);
	$this->db->or_like('tipo', $q);
	$this->db->or_like('cepa', $q);
	$this->db->or_like('anio', $q);
	$this->db->or_like('pais', $q);
	$this->db->or_like('imagen', $q);
	$this->db->or_like('color', $q);
	$this->db->or_like('nariz', $q);
	$this->db->or_like('boca', $q);
	$this->db->or_like('maridaje', $q);
	$this->db->or_like('precio', $q);
	$this->db->or_like('descripcion', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Vinos_model.php */
/* Location: ./application/models/Vinos_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-04-27 21:12:31 */
/* http://harviacode.com */